import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { DEMO_JOB_ID } from '../server/src/demo.js';

const suite = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// A minimal, valid PDF with a cross-reference table. Its text declares the fixture.
function fictionalPdf() {
  const text = 'BT /F1 15 Tf 40 750 Td (Alex Example - SYNTHETIC CV) Tj 0 -28 Td (Fictional React and Node.js project experience. Demo only.) Tj ET';
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>', `<< /Length ${Buffer.byteLength(text)} >>\nstream\n${text}\nendstream`];
  let pdf = '%PDF-1.4\n'; const offsets = [0];
  objects.forEach((obj, i) => { offsets.push(Buffer.byteLength(pdf)); pdf += `${i + 1} 0 obj\n${obj}\nendobj\n`; });
  const xref = Buffer.byteLength(pdf);
  pdf += `xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n => String(n).padStart(10, '0') + ' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return pdf;
}

export async function startDemoBackend({ port = 5075 } = {}) {
  const origin = `http://127.0.0.1:${port}`;
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'sajas-synthetic-'));
  const cvPath = path.join(directory, 'generated-docs', 'synthetic-cv.pdf');
  await fs.mkdir(path.dirname(cvPath));
  await fs.writeFile(cvPath, fictionalPdf());
  await fs.writeFile(path.join(directory, 'keys.json'), '{}', { mode: 0o600 });
  await fs.writeFile(path.join(directory, 'db.json'), JSON.stringify({
    profile: { fullName: 'Alex Example', email: 'alex@example.test', phone: '0000000000',
      baseCv: 'SYNTHETIC CV. Alex Example builds fictional React and Node.js projects. No real qualifications or applicant records are represented.',
      keywords: 'Software Engineer, React, Node.js', locations: 'Johannesburg, Remote',
      applicationProfile: { rightToWorkSA: 'Yes', noticePeriod: '30 days' },
      useAiSearch: false, useLinkValidation: false, useLinkRepair: false,
      useAiPlanner: false, useVision: false, useComputerUse: false,
      useResearchFanout: false, useDreaming: false, useMemoryReflection: false },
    jobs: [{ id: DEMO_JOB_ID, title: 'Software Engineer', company: 'Example Studio',
      location: 'Johannesburg · Hybrid', source: 'Synthetic local fixture', matchScore: 82,
      description: 'FICTIONAL VACANCY: develop React and Node.js applications with clear tests. This role, employer and score are demonstration data.',
      applyUrl: `${origin}/demo/jobs/software-engineer`, status: 'tailored',
      tailoredCvText: 'SYNTHETIC CV — Alex Example\n\nFictional React and Node.js project experience. Handwritten demo text; not generated by AI.',
      tailoredCoverLetterText: 'SYNTHETIC LETTER — Alex Example would like to discuss the fictional software role at Example Studio. This is a handwritten fixture, not an AI output.',
      tailoredCvPath: cvPath, createdAt: new Date().toISOString() }],
    answerBank: [['Full name', 'Alex Example'], ['Email address', 'alex@example.test'], ['Phone number', '0000000000']]
      .map(([question, answer], index) => ({ id: `synthetic-answer-${index}`, question,
        normalized: question.toLowerCase(), answer, createdAt: new Date().toISOString() })),
    pendingQuestions: [], routines: [], logs: []
  }, null, 2));
  const env = { ...process.env, PORT: String(port), HOST: '127.0.0.1', SAJAS_DEMO_ORIGIN: origin,
    DB_PATH: path.join(directory, 'db.json'), KEYS_PATH: path.join(directory, 'keys.json'),
    BROWSER_PROFILE_PATH: path.join(directory, 'browser-profile'),
    GENERATED_DOCS_PATH: path.join(directory, 'generated-docs'),
    SUPPORTING_DOCS_PATH: path.join(directory, 'supporting-docs') };
  const child = spawn(process.execPath, ['server/src/index.js'], {
    cwd: suite, env, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe', 'ipc']
  });
  let output = ''; child.stdout.on('data', b => { output += b; }); child.stderr.on('data', b => { output += b; });
  let spawnError; child.on('error', error => { spawnError = error; });
  let stopped = false;
  const stop = async () => {
    if (stopped) return; stopped = true;
    if (child.exitCode === null && !spawnError) {
      const ended = new Promise(resolve => child.once('exit', resolve));
      if (child.connected) child.send({ type: 'stop-demo' }); else child.kill();
      const timer = setTimeout(() => child.kill(), 8000);
      await ended; clearTimeout(timer);
    }
    // Only remove the exact directory returned by mkdtemp, under the OS temp root.
    if (path.dirname(directory) !== path.resolve(os.tmpdir()) || !path.basename(directory).startsWith('sajas-synthetic-')) {
      throw new Error('Refusing to remove an unexpected demo directory.');
    }
    await fs.rm(directory, { recursive: true, force: true });
  };
  try {
    const deadline = Date.now() + 15000;
    while (Date.now() < deadline) {
      if (spawnError) throw spawnError;
      if (child.exitCode !== null) throw new Error(output || 'Demo backend exited.');
      try {
        const response = await fetch(`${origin}/api/demo`, { signal: AbortSignal.timeout(500) });
        if (response.ok && (await response.json()).synthetic) {
          // Ensure this is OUR process, not another server on an occupied port.
          if (output.includes('[SA-JAS Server] Backend running')) return { origin, directory, env, stop };
        }
      } catch {}
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    throw new Error('Demo startup timed out.\n' + output);
  } catch (error) { await stop(); throw error; }
}
